### ISSUE TITLE
Configure does not find zlib but claims it is enabled

### ISSUE THREAD

**Issue by andreasstieger** [ColumPaget/libUseful#11]
Configure does not find zlib but claims it is enabled:

````
[    5s] checking for deflate in -lz... no
[...]
[    5s] zlib support enabled
````

`configure.ac` prints on `use_...` , not `have_...`

**Comment by ColumPaget** [comment]
good catch. Corrected, along with a few other things, in v5.9.

Thanks again for all your work on libUseful!
