### ISSUE TITLE
library has no soname

### ISSUE THREAD

**Issue by andreasstieger** [ColumPaget/libUseful#13]
The shared library does not have an `soname`. From my built (an rpmlint check):

````
[   25s] libUseful.x86_64: W: no-soname /usr/lib/libUseful-5.9.so
[   25s] The library has no soname.
````

**Comment by ColumPaget** [comment]
this is something I've never even heard of before... I'll look into fitting it in the next release. I'm guessing the soname should be 'libUseful.so.5?

**Comment by andreasstieger** [comment]
Since you never had one you would start at 0. You could do the [libtool](https://www.gnu.org/software/libtool/manual/html_node/Libtool-versioning.html) way.

**Comment by ColumPaget** [comment]
added, didn't start at 0 for fears of it becoming unmanageable, the major release number generally means 'new api'. It's default 'on' under gcc, off otherwise but can be enabled with --enable-soname
