### ISSUE TITLE
PBASE64_CHARS is not rfc 4648 compliant

### ISSUE THREAD

**Issue by jvw1954** [ColumPaget/libUseful#3]
[https://github.com/ColumPaget/libUseful/blob/master/Encodings.h](https://github.com/ColumPaget/libUseful/blob/master/Encodings.h):

>#define BASE64_CHARS "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
...
#define PBASE64_CHARS "0123456789-ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"

This last line is not [rfc 4648](https://www.ietf.org/rfc/rfc4648.txt) compliant. It must be:
#define PBASE64_CHARS "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"

See also: [https://github.com/ColumPaget/Hashrat/issues/18](https://github.com/ColumPaget/Hashrat/issues/18)

**Comment by ColumPaget** [comment]
Closing due to it being fixed some time ago, but only the hashrat issue was closed, not the libUseful one.

Thanks again to jvw1954 for finding this.

**Comment by ColumPaget** [comment]
really closing this time!
